### ISSUE TITLE
GML-Highscorer

### ISSUE THREAD

**Issue by Grisgram** [tabularelf/gamemaker-kitchen#156]
### What kind of resource is this?

Library

### Logo

https://www.coldrock.games/assets/raptor/gml-highscorer-logo.png

### Description

A highly configurable, fast renderer for Highscore tables for your arcade style games. Supports lowest/highest score, lowest/highest time, can render trophies for the top 3, various fonts and coloring supported.

### Authors

Grisgram

### Link to your resource

https://github.com/Grisgram/gml-highscorer

### Tags

Arcade, Gamejam, Highscores

## Here's what it can look like
This screenshot is taken from the demo program contained in the repository. 
Just open the project in GameMaker Studio and hit F5, so you can play around with the settings and take a closer look in the room, where variables are set for the renderers.<br/>
* Date and Time format are localized based on the device settings!
* Columns can be turned on/off at will
* Colors can be changed
* Supports 3-999 Ranks (likely more, but I tested only up to 999)

![screen_default_score](https://raw.githubusercontent.com/Grisgram/gml-highscorer/412a6f0967bc05eb45aaf694764c310289454e81/_assets_/demo-screenshot.jpg)

### What versions does your resource support?

- [ ] LTS+
- [X] 2023.1+
- [ ] 2024.2+
- [ ] Latest current runtime version (local packages)
- [ ] Latest current runtime version (prefabs)
- [ ] New runtime (local packages)
- [ ] New runtime (prefabs)
- [X] I've selected a version per above

### What platforms has this been tested on?

- [X] Windows
- [ ] MacOSX
- [ ] Linux
- [X] HTML5/GX.games
- [ ] iOS
- [ ] Android
- [ ] Consoles
- [ ] All of the above

**Comment by tabularelf** [comment]
Added
