### ISSUE TITLE
GML-Animated Flag

### ISSUE THREAD

**Issue by Grisgram** [tabularelf/gamemaker-kitchen#157]
### What kind of resource is this?

Library

### Logo

https://www.coldrock.games/assets/raptor/gml-animated-flag-logo.png

### Description

Vertex-based real-time rendering of any sprite resource as a waving flag in the wind

### Authors

Grisgram

### Link to your resource

https://github.com/Grisgram/gml-animated-flag

### Tags

Animation, Vertex, Sprites

### Post

A simple, vertex based animation, that offers many settings to customize:

![settings](https://raw.githubusercontent.com/Grisgram/gml-animated-flag/main/_assets_/variable-settings.jpg)

| Variable | Description |
|-|-|
| `animation_fps`	| how many frames shall be calculated?|
| `intensity`		| how many waves are on the flag|
| `wave_speed`		| how fast do the waves move|
| `wave_height`		| how strong are the waves|
| `vertex_count`	| if -1, then default of 10% of sprite width|
| `render_width`	| if -1, then image_xscale as set in room editor|
| `render_height`	| if -1, then image_yscale as set in room editor|

Here's a screenshot of the demo room in the repository

![demo-screen](https://raw.githubusercontent.com/Grisgram/gml-animated-flag/main/_assets_/demo-screenshot.jpg)

### What versions does your resource support?

- [ ] LTS+
- [X] 2023.1+
- [ ] 2024.2+
- [ ] Latest current runtime version (local packages)
- [ ] Latest current runtime version (prefabs)
- [ ] New runtime (local packages)
- [ ] New runtime (prefabs)
- [X] I've selected a version per above

### What platforms has this been tested on?

- [X] Windows
- [ ] MacOSX
- [ ] Linux
- [X] HTML5/GX.games
- [ ] iOS
- [ ] Android
- [ ] Consoles
- [ ] All of the above

**Comment by tabularelf** [comment]
Added!
