### ISSUE TITLE
Submission: Catspeak

### ISSUE THREAD

**Issue by katsaii** [tabularelf/gamemaker-kitchen#159]
### What kind of resource is this?

Library

### Logo

https://raw.githubusercontent.com/katsaii/catspeak-lang/main/catspeak-logo.svg

### Description

A cross-platform modding language for GameMaker games.

### Authors

Katsaii

### Link to your resource

https://github.com/katsaii/catspeak-lang

### Tags

modding, debug, lts

### Post

Catspeak is the spiritual successor to the long dead `execute_string` function from GameMaker 8.1, but on overdrive.

Use the built-in Catspeak scripting language to expose **safe** and **sandboxed** modding APIs within GameMaker projects, or bootstrap your own domain-specific languages and development tools using the back-end code generation tools offered by Catspeak.

Compile performant scripts from plain-text...
```gml
// parse Catspeak code
var ir = Catspeak.parseString(@'
  let catspeak = "Catspeak"

  return "hello! from within " + catspeak
');

// compile Catspeak code into a callable GML function
var getMessage = Catspeak.compileGML(ir);

// call the Catspeak code just like you would any other GML function!
show_message(getMessage());
```
...without giving modders unrestricted access to your sensitive game code:
```gml
var ir = Catspeak.parseString(@'
  game_end(); -- heheheh, my mod will make your game close >:3
');

// calling `badMod` will throw an error instead
// of calling the `game_end` function
try {
  var badMod = Catspeak.compileGML(ir);
  badMod();
} catch (e) {
  show_message("a mod did something bad!");
}
```

### What versions does your resource support?

- [X] LTS+
- [ ] 2023.1+
- [ ] 2024.2+
- [ ] Latest current runtime version (local packages)
- [ ] Latest current runtime version (prefabs)
- [ ] New runtime (local packages)
- [ ] New runtime (prefabs)
- [X] I've selected a version per above

### What platforms has this been tested on?

- [X] Windows
- [ ] MacOSX
- [ ] Linux
- [X] HTML5/GX.games
- [ ] iOS
- [ ] Android
- [ ] Consoles
- [ ] All of the above

**Comment by tabularelf** [comment]
Added d3a15b9961cfc730c123b0599d1cbd4f1eb281bd
