### ISSUE TITLE
Submission: Post-Processing FX

### ISSUE THREAD

**Issue by FoxyOfJungle** [tabularelf/gamemaker-kitchen#162]
### What kind of resource is this?

Asset

### Logo

https://kazangames.com/assets/ppfx/icon.png

### Description

Efficient, easy-to-use and compact post-processing library

### Authors

FoxyOfJungle

### Link to your resource

https://kazangames.com/assets/ppfx/

### Tags

effects, filters, post-processing, ACES, color grading, shockwaves, bloom

### Post

The most efficient, easiest and robust post-processing library available for GameMaker.

Post-processing is a generic term for a full-screen image processing effect that occurs after the overall rendering of the game. Post-processing can drastically improve the visuals of your game with little setup time.

The image below demonstrate a scene without and with post-processing:

![PPFX_Comparison](https://github.com/tabularelf/gamemaker-kitchen/assets/52144406/53dfb671-2c4d-4882-9b96-af97c251371d)

Using the optional UI to edit effects in real time:

![8QViWvF](https://github.com/tabularelf/gamemaker-kitchen/assets/52144406/6c0429c4-efc4-44b0-b621-47f0850fd6cd)

Post-Processing FX is a library that contains not only effects, but many useful related features. Check everything out on the [website](https://kazangames.com/assets/ppfx/).

Check out the [documentation](https://kazangames.com/assets/ppfx/docs/) too!

### Does your resource support LTS?

- [X] Yes
- [ ] No

### What platforms has this been tested on?

- [X] Windows
- [X] MacOSX
- [X] Linux
- [X] HTML5/GX.games
- [X] iOS
- [X] Android
- [X] Consoles
- [X] All of the above

**Comment by tabularelf** [comment]
Added!
