### ISSUE TITLE
Submission: Managix

### ISSUE THREAD

**Issue by FoxyOfJungle** [tabularelf/gamemaker-kitchen#163]
### What kind of resource is this?

Asset

### Logo

https://kazangames.com/assets/managix/icon.png

### Description

Game memory optimizer (with async load/save support)

### Authors

FoxyOfJungle

### Link to your resource

https://kazangames.com/assets/managix/

### Tags

optimization, memory, async, loading, saving, buffers, texture pages, audio groups

### Post

Has your game ever crashed your device because it used too much memory?

This is the ultimate solution for asynchronous loading and saving (withou freezing the game). Must-needed for resource-intensive games (or if you want to optimize your game's memory usage in general).

With Managix, load only what is needed in each room, such as texture pages, audio groups, particles, buffers (3D models, etc)

![PZkksJ](https://github.com/tabularelf/gamemaker-kitchen/assets/52144406/1870c6b1-e032-4756-aa72-f09faccbecaf)

Supports saving/loading buffers to console slots, plus several super useful features. [Check it all out here](https://foxyofjungle.itch.io/managix).

Also, there is a [documentation](https://kazangames.com/assets/managix/docs/v1/).

### Does your resource support LTS?

- [ ] Yes
- [X] No

### What platforms has this been tested on?

- [X] Windows
- [X] MacOSX
- [X] Linux
- [X] HTML5/GX.games
- [X] iOS
- [X] Android
- [X] Consoles
- [X] All of the above

**Comment by tabularelf** [comment]
Added
