### ISSUE TITLE
Submission: TurboGML

### ISSUE THREAD

**Issue by FoxyOfJungle** [tabularelf/gamemaker-kitchen#164]
### What kind of resource is this?

Library

### Logo

https://github.com/FoxyOfJungle/TurboGML/blob/main/ICON.png

### Description

The largest collection of useful general GML functions

### Authors

FoxyOfJungle

### Link to your resource

https://github.com/FoxyOfJungle/TurboGML

### Tags

functions, scripts, useful, math, file search, strings, arrays

### Post

The largest collection of useful general GML functions (Math, AI, Linear Algebra, Arrays, Structs, Strings, File Search, Paths, Conversions etc)

The purpose of this library is to contain functions for common use, aimed at game development. So it was made thinking about being used in its entirety, rather than in parts.

At some point you will use the functions, although their existence or not will not affect your project. After all, the library is only a few kb! :D

Lately, I import it in all my new game projects! 🔥

There's a lot of cool and useful stuff! [Check it all out here](https://github.com/FoxyOfJungle/TurboGML).

### Does your resource support LTS?

- [X] Yes
- [ ] No

### What platforms has this been tested on?

- [X] Windows
- [X] MacOSX
- [X] Linux
- [X] HTML5/GX.games
- [X] iOS
- [X] Android
- [X] Consoles
- [X] All of the above

**Comment by tabularelf** [comment]
This is technically a duplicate of #91, however I always prefer manual submissions so I'll be yoinking this.

**Comment by tabularelf** [comment]
In the future I'd like to ask for you to get a raw image logo. That is all! Added

**Comment by FoxyOfJungle** [comment]
Hey! raw in what sense? Wouldn't this logo be raw? I uploaded it "as-is" 🤔

**Comment by tabularelf** [comment]
> Hey! raw in what sense? Wouldn't this logo be raw? I uploaded it "as-is" 🤔

Github itself does allow uploading images, but the url links don't actually point to the raw equivilant, which is used to share the image itself across sites. [https://raw.githubusercontent.com/FoxyOfJungle/TurboGML/main/ICON.png](https://raw.githubusercontent.com/FoxyOfJungle/TurboGML/main/ICON.png)

**Comment by FoxyOfJungle** [comment]
Oh! I actually tried to do this, even opening the page in the incognito mode, but I didn't understand how to get this type of link

**Comment by tabularelf** [comment]
There's two ways of doing that. 
1. Apply `?raw=true` at the end of the image url, that'll load up the raw equivilant.
2. Right click on image -> open image in new tab (will do the exact same as above)
