### ISSUE TITLE
Libraries page UI feature request 

### ISSUE THREAD

**Issue by EdensStudio** [tabularelf/gamemaker-kitchen#165]
![image](https://github.com/tabularelf/gamemaker-kitchen/assets/83062244/d53de4dc-5e65-42d2-9e16-5be6954fcb07)
Adding the feature for showing how many pages and selecting them like
`< 1  2  3  4  ...  10 >`
would be nice

**Comment by tabularelf** [comment]
Would be good to make a separate issue for the banner bug, rather than tackling it all under one... I will do this for you this one time, but next time please make separate issues
