### ISSUE TITLE
Submission: Good Vibes

### ISSUE THREAD

**Issue by mrdaneeyul** [tabularelf/gamemaker-kitchen#71]
### What kind of resource is this?

Library

### Description

Good Vibes

### Authors

daneeyul

### Link to your resource

https://github.com/mrdaneeyul/good-vibes

### Tags

vibration, gamepad, rumble, controller

### Post

This is a GameMaker Studio 2 plugin for device vibration! This plugin allows for simple or complex timed vibrations.

Normally, GameMaker will just vibrate a gamepad until you manually turn it off; this plugin handles that for you. You can set the duration of the vibration in frames independently for left and right motors.

This plugin also can make use of animation curves to allow for complex vibration patterns. Included are some sample patterns, including linear fadein, fadeout, panning between motors, and square wave pulses.

### What versions does your resource support?

- [X] LTS
- [ ] 2023.1+
- [ ] 2024.4+
- [ ] Latest current runtime version (local packages)
- [ ] Latest current runtime version (prefabs)
- [ ] New runtime (local packages)
- [ ] New runtime (prefabs)
- [X] I've selected a version per above

### What platforms has this been tested on?

- [X] Windows
- [ ] MacOSX
- [ ] Linux
- [ ] HTML5/GX.games
- [ ] iOS
- [ ] Android
- [ ] Consoles
- [ ] All of the above

**Comment by tabularelf** [comment]
In the future I'll ask to provide a proper description. Using `GameMaker Studio 2 plugin for gamepad vibration`. Added (pending alongside a couple other submissions to be published)
