### ISSUE TITLE
Add link to GitHub in footer

### ISSUE THREAD

**Issue by JujuAdams** [tabularelf/gamemaker-kitchen#74]
The header/footer of the website currently has helpful links such as "Authors" "Tags" "Discord" etc.  It's likely that many users of the website will want to contribute libraries as well as use them. A link to this GitHub (perhaps directly to resource submission?) would smooth out the user experience and make contributions more frequent.

**Comment by tabularelf** [comment]
I've made a link to the repository itself on the website just now, but I'll be adapting the readme as per #75 to include that (as well as the wiki itself). Problem with linking directly to resource submission is that one isn't able to view the rest of the areas involved, as there are many ways one can contribute. The wiki has it as a simplified outline, but I'll be slowly looking at correcting and expanding upon the wiki over the course of the next couple weeks. (it's more easier to document and manage on there than spinning up another docsify instance directly)
