### ISSUE TITLE
Submission: SNAP

### ISSUE THREAD

**Issue by JujuAdams** [tabularelf/gamemaker-kitchen#76]
### What kind of resource is this?

Library

### Description

Data format converters

### Authors

Juju Adams

### Link to your resource

https://github.com/JujuAdams/SNAP

### Tags

data

### Post

SNAP is a set of data format converters packaged with struct/array utilities. The following data formats are supported:
- JSON (including comments)
- YAML
- CSV
- Messagepack
- XML
- INI (read only)
- VDF
- QML
- Null-separated value files (fast CSVs)
- Custom fast binary format
- Custom grid and 2D array format
- Custom tilemap format

### What versions does your resource support?

- [X] LTS
- [ ] 2023.1+
- [ ] 2024.2+
- [ ] Latest current runtime version (local packages)
- [ ] Latest current runtime version (prefabs)
- [ ] New runtime (local packages)
- [ ] New runtime (prefabs)
- [X] I've selected a version per above

### What platforms has this been tested on?

- [X] Windows
- [X] MacOSX
- [X] Linux
- [ ] HTML5/GX.games
- [X] iOS
- [X] Android
- [X] Consoles
- [ ] All of the above

**Comment by tabularelf** [comment]
Added.
