### ISSUE TITLE
Submission: Snitch

### ISSUE THREAD

**Issue by JujuAdams** [tabularelf/gamemaker-kitchen#78]
### What kind of resource is this?

Library

### Description

Logging and crash handling system

### Authors

Juju Adams 

### Link to your resource

https://github.com/JujuAdams/Snitch

### Tags

logging, error

### Post

Snitch is a logging and crash tracking system. During development, Snitch can help you debug challenging situations through its comprehensive logging, including UDP broadcasts. In production, Snitch can catch crashes and exceptions and route that information to a bug tracking service of your choosing.

Snitch supports REST APIs for the following services:
- sentry.io
- GameAnalytics
- Bug Snag
- Generic error reporting endpoints

### What versions does your resource support?

- [X] LTS
- [ ] 2023.1+
- [ ] 2024.2+
- [ ] Latest current runtime version (local packages)
- [ ] Latest current runtime version (prefabs)
- [ ] New runtime (local packages)
- [ ] New runtime (prefabs)
- [X] I've selected a version per above

### What platforms has this been tested on?

- [X] Windows
- [X] MacOSX
- [X] Linux
- [ ] HTML5/GX.games
- [X] iOS
- [X] Android
- [X] Consoles
- [ ] All of the above

**Comment by tabularelf** [comment]
Added.
