### ISSUE TITLE
Submission: iota

### ISSUE THREAD

**Issue by JujuAdams** [tabularelf/gamemaker-kitchen#79]
### What kind of resource is this?

Library

### Description

Miniature fixed timestep library

### Authors

Juju Adams 

### Link to your resource

https://github.com/JujuAdams/iota

### Tags

time, delta time

### Post

iota is a teeny tiny [fixed timestep](https://gafferongames.com/post/fix_your_timestep/) library that handles different framerates automatically for you. You can also set up time dilation for slowmo effects. Multiple "clocks" can run at the same time allowing you to pause different parts of your game easily.

### What versions does your resource support?

- [X] LTS
- [ ] 2023.1+
- [ ] 2024.2+
- [ ] Latest current runtime version (local packages)
- [ ] Latest current runtime version (prefabs)
- [ ] New runtime (local packages)
- [ ] New runtime (prefabs)
- [X] I've selected a version per above

### What platforms has this been tested on?

- [X] Windows
- [X] MacOSX
- [X] Linux
- [ ] HTML5/GX.games
- [X] iOS
- [X] Android
- [X] Consoles
- [ ] All of the above

**Comment by tabularelf** [comment]
Added.
