### ISSUE TITLE
Submission: Bulb

### ISSUE THREAD

**Issue by JujuAdams** [tabularelf/gamemaker-kitchen#80]
### What kind of resource is this?

Library

### Description

2D lighting and shadows

### Authors

Juju Adams

### Link to your resource

https://github.com/JujuAdams/Bulb

### Tags

light, shadows

### Post

Bulb is a 2D lighting solution designed for ease-of-use and speed. Shadows are cast by defined geometric shapes with "edges". Point lights, conical (shaped) lights, and directional (sunlight) lights are supported and can be accumulated using either additive or "bm_max" blend modes. Shadows can be hard shadows or a fast approximation of soft shadows that doesn't use any blurring.

### What versions does your resource support?

- [X] LTS
- [ ] 2023.1+
- [ ] 2024.2+
- [ ] Latest current runtime version (local packages)
- [ ] Latest current runtime version (prefabs)
- [ ] New runtime (local packages)
- [ ] New runtime (prefabs)
- [X] I've selected a version per above

### What platforms has this been tested on?

- [X] Windows
- [X] MacOSX
- [X] Linux
- [ ] HTML5/GX.games
- [X] iOS
- [X] Android
- [X] Consoles
- [ ] All of the above

**Comment by tabularelf** [comment]
Added.
