### ISSUE TITLE
Submission: Clean Shapes

### ISSUE THREAD

**Issue by JujuAdams** [tabularelf/gamemaker-kitchen#81]
### What kind of resource is this?

Library

### Description

Antialiased primitive drawing

### Authors

Juju Adams

### Link to your resource

https://github.com/JujuAdams/Clean-Shapes

### Tags

geometry, primitives, antialiasing

### Post

Clean Shapes is a primitive-drawing library that generates antialiased graphics for use alongside other antialiased artwork. Shapes can be batched together for efficient rendering.

The following primitives are supported:
- Line
- Polyline
- Spline
- Rectangle
- Capsule
- Circle
- Ellipse
- Segment
- Ring
- Triangle
- Convex polygon
- Regular n-gon

### What versions does your resource support?

- [X] LTS
- [ ] 2023.1+
- [ ] 2024.2+
- [ ] Latest current runtime version (local packages)
- [ ] Latest current runtime version (prefabs)
- [ ] New runtime (local packages)
- [ ] New runtime (prefabs)
- [X] I've selected a version per above

### What platforms has this been tested on?

- [X] Windows
- [X] MacOSX
- [X] Linux
- [ ] HTML5/GX.games
- [X] iOS
- [X] Android
- [X] Consoles
- [ ] All of the above

**Comment by tabularelf** [comment]
Added.
